{% set name = "libatomic_ops" %}
{% set version = "7.8.2" %}
{% set sha256 = "d305207fe207f2b3fb5cb4c019da12b44ce3fcbc593dfd5080d867b1a2419b51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("libatomic_ops", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool                 # [unix]
    - make                    # [unix]
    - cmake                   # [win]
    - ninja                   # [win]
  host:

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h               # [unix]
    - test -e $PREFIX/lib/libatomic_ops${SHLIB_EXT}      # [unix]
    - if not exist %LIBRARY_INC%\\atomic_ops.h exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\atomic_ops.dll exit 1  # [win]

about:
  home: https://github.com/ivmai/libatomic_ops
  license: MIT AND GPL-2.0-or-later
  license_file: LICENSE
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
    - saraedum
    - isuruf
