{% set name = "libatomic_ops" %}
{% set version = "7.8.2" %}
{% set sha256 = "d305207fe207f2b3fb5cb4c019da12b44ce3fcbc593dfd5080d867b1a2419b51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - make
  host:

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h
    - test -e $PREFIX/lib/libatomic_ops.a

about:
  home: https://github.com/ivmai/libatomic_ops
  license: MIT AND GPL-2.0-or-later
  license_file: doc/LICENSING.txt
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
    - saraedum
    - isuruf
