{% set name = "libatomic_ops" %}
{% set version = "7.6.8" %}
{% set sha256 = "1d6a279edf81767e74d2ad2c9fce09459bc65f12c6525a40b0cb3e53c089f665" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ivmai/{{ name }}/releases/download/v{{ version }}/libatomic_ops-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:

test:
  commands:
    - test -e $PREFIX/include/atomic_ops.h
    - test -e $PREFIX/lib/libatomic_ops.a

about:
  home: https://github.com/ivmai/libatomic_ops
  license: Custom
  summary: Implementations for atomic memory update operations.

extra:
  recipe-maintainers:
    - stefan-balke
    - saraedum
